version: '2' 

services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    #command: flask run --host 0.0.0.0 --port 5000
    depends_on:
      - redis
      - postgres

  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_HOSTNAME=${RDS_HOSTNAME}
      - POSTGRES_PORT=${RDS_PORT}
      - POSTGRES_DB=${RDS_DB_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  client:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - .:/home/ubuntu/celery-scheduler/
      - /home/ubuntu/celery-scheduler/node_modules
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_RACES_SERVICE_URL='https://]ocalhost:8080/data/races/all'
    depends_on:
      - app

