version: '2' 

services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
  
  celery:
    build: .
    command: celery -A app.tasks worker -B -l info
    user: nobody
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - postgres

  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_HOSTNAME=${RDS_HOSTNAME}
      - POSTGRES_DB=${RDS_DB_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  client:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - .:/home/ubuntu/celery-scheduler/
      - /home/ubuntu/celery-scheduler/node_modules
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_RACES_SERVICE_URL=https://]ocalhost:5000/api/races
    depends_on:
      - app

